CREATE TABLE `pacientes` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(50) NOT NULL DEFAULT '0',
	`apellido` VARCHAR(50) NOT NULL DEFAULT '0',
	`nacimiento` DATE NOT NULL DEFAULT '0000-00-00',
	`sexo` VARCHAR(50) NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
)
ENGINE=InnoDB
;
